In [5]:
import pandas as pd
import os
from glob import glob

out = pd.DataFrame()

no_qb3 = pd.read_csv('/data/henry7/james/antje_cohort/no_qb3_antje_transition_cohort.csv')
qb3 = pd.read_csv('/data/henry7/james/antje_cohort/qb3_antje_transition_cohort.csv')
print(no_qb3)
print(qb3)

       msid        date      mse           scanner  \
0      ms69  2005-04-20  mse1343       CB3TMR (3T)
1      ms69  2006-05-02  mse1344       CB3TMR (3T)
2      ms69  2007-04-10  mse1345       CB3TMR (3T)
3      ms69  2008-05-20  mse1346       CB3TMR (3T)
4      ms69  2009-04-08  mse1347       CB3TMR (3T)
5      ms69  2010-04-08  mse1348       CB3TMR (3T)
6      ms69  2013-05-22  mse4287   UCSF-NUMR2 (3T)
7      ms71  2005-03-23  mse1355       CB3TMR (3T)
8      ms71  2006-05-17  mse1356       CB3TMR (3T)
9      ms71  2007-06-19  mse1357       CB3TMR (3T)
10     ms71  2008-08-27  mse1358       CB3TMR (3T)
11     ms71  2009-08-05  mse1359       CB3TMR (3T)
12     ms71  2010-08-03  mse1360      CB-3TMR (3T)
13     ms71  2013-05-13  mse4291   UCSF-NUMR2 (3T)
14     ms71  2015-06-18  mse3041   UCSF-NUMR2 (3T)
15     ms71  2016-04-12  mse5276   UCSF-NUMR2 (3T)
16     ms73  2005-04-13  mse1361       CB3TMR (3T)
17     ms73  2006-04-05  mse1362       CB3TMR (3T)
18     ms73  2007-03-14  mse1363       CB3TMR (3T)
19     ms73  2008-06-19  mse1364       CB3TMR (3T)
20     ms73  2009-07-09  mse1365       CB3TMR (3T)
21     ms73  2010-06-10  mse1366      CB-3TMR (3T)
22     ms73  2014-05-07  mse4292   UCSF-NUMR2 (3T)
23     ms73  2014-05-07  mse4293   UCSF-NUMR2 (3T)
24    ms170  2005-02-01     mse1       CB3TMR (3T)
25    ms170  2006-02-28  mse1395       CB3TMR (3T)
26    ms170  2007-01-31     mse2       CB3TMR (3T)
27    ms170  2008-03-27  mse1396       CB3TMR (3T)
28    ms170  2009-01-14  mse1397       CB3TMR (3T)
29    ms170  2009-12-17  mse1398       CB3TMR (3T)
..      ...         ...      ...               ...
749  ms1292  2005-08-30  mse2598       CB3TMR (3T)
750  ms1292  2006-08-31  mse2599       CB3TMR (3T)
751  ms1292  2007-09-26  mse2600       CB3TMR (3T)
752  ms1292  2008-09-02  mse2601       CB3TMR (3T)
753  ms1292  2009-08-20  mse2602       CB3TMR (3T)
754  ms1292  2013-10-16  mse4660   UCSF-NUMR2 (3T)
755  ms1292  2015-12-02  mse4073   UCSF-NUMR2 (3T)
756  ms1292  2016-11-09  mse7140   UCSF-NUMR2 (3T)
757  ms1300  2005-09-01  mse2634       CB3TMR (3T)
758  ms1300  2006-09-06  mse2635       CB3TMR (3T)
759  ms1369  2008-01-31  mse2656       CB3TMR (3T)
760  ms1369  2009-01-21  mse2657       CB3TMR (3T)
761  ms1369  2010-01-14  mse2658       CB3TMR (3T)
762  ms1369  2010-12-02  mse2659      CB-3TMR (3T)
763  ms1369  2013-05-20  mse4670   UCSF-NUMR2 (3T)
764  ms1369  2014-08-13  mse4671   UCSF-NUMR2 (3T)
765  ms1369  2015-10-01  mse3671   UCSF-NUMR2 (3T)
766  ms1369  2017-01-12  mse7421   UCSF-NUMR2 (3T)
767  ms1462  2008-04-24  mse2691       CB3TMR (3T)
768  ms1462  2009-03-10  mse2692       CB3TMR (3T)
769  ms1462  2010-03-18  mse2693       CB3TMR (3T)
770  ms1462  2013-01-30  mse7538     AWP45386 (3T)
771  ms1462  2015-05-06  mse2908   UCSF-NUMR2 (3T)
772  ms1462  2016-07-27  mse6565   UCSF-NUMR2 (3T)
773  ms1578  2011-01-26  mse4238  UCSF-ZMOB3T (3T)
774  ms1578  2011-06-21  mse4782      CB-3TMR (3T)
775  ms1578  2013-07-23  mse4702   UCSF-NUMR2 (3T)
776  ms1578  2014-08-27  mse4703   UCSF-NUMR2 (3T)
777  ms1578  2015-06-15  mse3029   UCSF-NUMR2 (3T)
778  ms1578  2016-07-05  mse5854   UCSF-NUMR2 (3T)

                                                folder
0                  /data/pelletier/EPIC/ms0069/mse1343
1                  /data/pelletier/EPIC/ms0069/mse1344
2                  /data/pelletier/EPIC/ms0069/mse1345
3                  /data/pelletier/EPIC/ms0069/mse1346
4                  /data/pelletier/EPIC/ms0069/mse1347
5    /henry_temp/jayaji/archive_dir_tmp_t1348/ms69/...
6     /henry7/EPIC8/archive_dir_tmp_t4287/ms69/mse4287
7                  /data/pelletier/EPIC/ms0071/mse1355
8                  /data/pelletier/EPIC/ms0071/mse1356
9                  /data/pelletier/EPIC/ms0071/mse1357
10                 /data/pelletier/EPIC/ms0071/mse1358
11                 /data/pelletier/EPIC/ms0071/mse1359
12   /henry_temp/jayaji/archive_dir_tmp_t1360/ms71/...
13     /henry8/EPIC/archive_dir_tmp_t4291/ms71/mse4291
14                     /data/henry7/EPIC8/ms71/mse3041
15                     /data/henry7/EPIC8/ms71/mse5276
16                 /data/pelletier/EPIC/ms0073/mse1361
17                 /data/pelletier/EPIC/ms0073/mse1362
18                 /data/pelletier/EPIC/ms0073/mse1363
19                 /data/pelletier/EPIC/ms0073/mse1364
20                 /data/pelletier/EPIC/ms0073/mse1365
21   /henry_temp/jayaji/archive_dir_tmp_t1366/ms73/...
22    /henry7/EPIC8/archive_dir_tmp_t4292/ms73/mse4292
23    /henry7/EPIC8/archive_dir_tmp_t4293/ms73/mse4293
24                    /data/pelletier/EPIC/ms0170/mse1
25                 /data/pelletier/EPIC/ms0170/mse1395
26                    /data/pelletier/EPIC/ms0170/mse2
27                 /data/pelletier/EPIC/ms0170/mse1396
28                 /data/pelletier/EPIC/ms0170/mse1397
29                 /data/pelletier/EPIC/ms0170/mse1398
..                                                 ...
749                /data/pelletier/EPIC/ms1292/mse2598
750                /data/pelletier/EPIC/ms1292/mse2599
751                /data/pelletier/EPIC/ms1292/mse2600
752                /data/pelletier/EPIC/ms1292/mse2601
753                /data/pelletier/EPIC/ms1292/mse2602
754  /henry7/EPIC8/archive_dir_tmp_t4660/ms1292/mse...
755                  /data/henry7/EPIC8/ms1292/mse4073
756           /working/henry_temp/EPIC8/ms1292/mse7140
757                /data/pelletier/EPIC/ms1300/mse2634
758                /data/pelletier/EPIC/ms1300/mse2635
759  /henry_temp/jayaji/EPIC_Upload_Errors/ms1369/m...
760  /henry_temp/jayaji/EPIC_Upload_Errors/ms1369/m...
761  /henry_temp/jayaji/EPIC_Upload_Errors/ms1369/m...
762  /henry_temp/jayaji/EPIC_Upload_Errors/ms1369/m...
763  /henry7/EPIC8/archive_dir_tmp_t4670/ms1369/mse...
764  /henry7/EPIC8/archive_dir_tmp_t4671/ms1369/mse...
765                  /data/henry7/EPIC8/ms1369/mse3671
766           /working/henry_temp/EPIC8/ms1369/mse7421
767                /data/pelletier/EPIC/ms1462/mse2691
768                /data/pelletier/EPIC/ms1462/mse2692
769                /data/pelletier/EPIC/ms1462/mse2693
770              /henry_temp/PBR/dicoms/ms1462/mse7538
771                  /data/henry7/EPIC8/ms1462/mse2908
772                  /data/henry7/EPIC8/ms1462/mse6565
773             /data/henry6/Transition/ms1578/mse4238
774                   /data/henry8/EPIC/ms1578/mse4782
775  /henry7/EPIC8/archive_dir_tmp_t4702/ms1578/mse...
776  /henry7/EPIC8/archive_dir_tmp_t4703/ms1578/mse...
777                  /data/henry7/EPIC8/ms1578/mse3029
778                  /data/henry7/EPIC8/ms1578/mse5854

[779 rows x 5 columns]
      msid        date      mse      scanner  \
0    ms170  2012-12-10  mse4868  qb3-3t (3T)
1    ms512  2012-12-12  mse4877  qb3-3t (3T)
2    ms513  2012-10-31  mse4878  qb3-3t (3T)
3    ms564  2012-10-22  mse4893  qb3-3t (3T)
4    ms568  2013-01-03  mse4894  qb3-3t (3T)
5    ms577  2012-11-05  mse4895  qb3-3t (3T)
6    ms667  2013-01-07  mse4905  qb3-3t (3T)
7    ms729  2013-01-24  mse4914  qb3-3t (3T)
8    ms756  2012-11-07  mse4916  qb3-3t (3T)
9    ms897  2012-08-23  mse4924  qb3-3t (3T)
10  ms1136  2012-11-28  mse4928  qb3-3t (3T)
11  ms1244  2012-10-15  mse2446  qb3-3t (3T)
12  ms1279  2012-10-01  mse4933  qb3-3t (3T)

                                               folder
0    /henry8/EPIC/archive_dir_tmp_t4868/ms170/mse4868
1    /henry8/EPIC/archive_dir_tmp_t4877/ms512/mse4877
2               /data/henry6/Transition/ms907/mse4878
3    /henry8/EPIC/archive_dir_tmp_t4893/ms564/mse4893
4    /henry8/EPIC/archive_dir_tmp_t4894/ms568/mse4894
5    /henry8/EPIC/archive_dir_tmp_t4895/ms577/mse4895
6    /henry8/EPIC/archive_dir_tmp_t4905/ms667/mse4905
7    /henry8/EPIC/archive_dir_tmp_t4914/ms729/mse4914
8    /henry8/EPIC/archive_dir_tmp_t4916/ms756/mse4916
9    /henry8/EPIC/archive_dir_tmp_t4924/ms897/mse4924
10  /henry8/EPIC/archive_dir_tmp_t4928/ms1136/mse4928
11  /henry8/EPIC/archive_dir_tmp_t2446/ms1244/mse2446
12  /henry8/EPIC/archive_dir_tmp_t4933/ms1279/mse4933

In [14]:
no_qb3.drop(no_qb3.columns[[3,4]], axis=1, inplace=True)

IndexError: index 3 is out of bounds for axis 1 with size 3

In [15]:
qb3.drop(qb3.columns[[3,4]], axis=1, inplace=True)

In [18]:
qb3
no_qb3

       msid        date      mse
0      ms69  2005-04-20  mse1343
1      ms69  2006-05-02  mse1344
2      ms69  2007-04-10  mse1345
3      ms69  2008-05-20  mse1346
4      ms69  2009-04-08  mse1347
5      ms69  2010-04-08  mse1348
6      ms69  2013-05-22  mse4287
7      ms71  2005-03-23  mse1355
8      ms71  2006-05-17  mse1356
9      ms71  2007-06-19  mse1357
10     ms71  2008-08-27  mse1358
11     ms71  2009-08-05  mse1359
12     ms71  2010-08-03  mse1360
13     ms71  2013-05-13  mse4291
14     ms71  2015-06-18  mse3041
15     ms71  2016-04-12  mse5276
16     ms73  2005-04-13  mse1361
17     ms73  2006-04-05  mse1362
18     ms73  2007-03-14  mse1363
19     ms73  2008-06-19  mse1364
20     ms73  2009-07-09  mse1365
21     ms73  2010-06-10  mse1366
22     ms73  2014-05-07  mse4292
23     ms73  2014-05-07  mse4293
24    ms170  2005-02-01     mse1
25    ms170  2006-02-28  mse1395
26    ms170  2007-01-31     mse2
27    ms170  2008-03-27  mse1396
28    ms170  2009-01-14  mse1397
29    ms170  2009-12-17  mse1398
..      ...         ...      ...
749  ms1292  2005-08-30  mse2598
750  ms1292  2006-08-31  mse2599
751  ms1292  2007-09-26  mse2600
752  ms1292  2008-09-02  mse2601
753  ms1292  2009-08-20  mse2602
754  ms1292  2013-10-16  mse4660
755  ms1292  2015-12-02  mse4073
756  ms1292  2016-11-09  mse7140
757  ms1300  2005-09-01  mse2634
758  ms1300  2006-09-06  mse2635
759  ms1369  2008-01-31  mse2656
760  ms1369  2009-01-21  mse2657
761  ms1369  2010-01-14  mse2658
762  ms1369  2010-12-02  mse2659
763  ms1369  2013-05-20  mse4670
764  ms1369  2014-08-13  mse4671
765  ms1369  2015-10-01  mse3671
766  ms1369  2017-01-12  mse7421
767  ms1462  2008-04-24  mse2691
768  ms1462  2009-03-10  mse2692
769  ms1462  2010-03-18  mse2693
770  ms1462  2013-01-30  mse7538
771  ms1462  2015-05-06  mse2908
772  ms1462  2016-07-27  mse6565
773  ms1578  2011-01-26  mse4238
774  ms1578  2011-06-21  mse4782
775  ms1578  2013-07-23  mse4702
776  ms1578  2014-08-27  mse4703
777  ms1578  2015-06-15  mse3029
778  ms1578  2016-07-05  mse5854

[779 rows x 3 columns]

In [26]:
len_qb3 = len(qb3['msid'])
qb3['qb3_scanner'] = pd.Series(['Yes'] * len_qb3, index=qb3.index)

In [27]:
len_no_qb3 = len(no_qb3['msid'])
no_qb3['qb3_scanner'] = pd.Series(['No'] * len_no_qb3, index=no_qb3.index)

In [30]:
frames = [no_qb3, qb3]
result = pd.concat(frames)
print(result)

       msid        date      mse qb3_scanner
0      ms69  2005-04-20  mse1343          No
1      ms69  2006-05-02  mse1344          No
2      ms69  2007-04-10  mse1345          No
3      ms69  2008-05-20  mse1346          No
4      ms69  2009-04-08  mse1347          No
5      ms69  2010-04-08  mse1348          No
6      ms69  2013-05-22  mse4287          No
7      ms71  2005-03-23  mse1355          No
8      ms71  2006-05-17  mse1356          No
9      ms71  2007-06-19  mse1357          No
10     ms71  2008-08-27  mse1358          No
11     ms71  2009-08-05  mse1359          No
12     ms71  2010-08-03  mse1360          No
13     ms71  2013-05-13  mse4291          No
14     ms71  2015-06-18  mse3041          No
15     ms71  2016-04-12  mse5276          No
16     ms73  2005-04-13  mse1361          No
17     ms73  2006-04-05  mse1362          No
18     ms73  2007-03-14  mse1363          No
19     ms73  2008-06-19  mse1364          No
20     ms73  2009-07-09  mse1365          No
21     ms73  2010-06-10  mse1366          No
22     ms73  2014-05-07  mse4292          No
23     ms73  2014-05-07  mse4293          No
24    ms170  2005-02-01     mse1          No
25    ms170  2006-02-28  mse1395          No
26    ms170  2007-01-31     mse2          No
27    ms170  2008-03-27  mse1396          No
28    ms170  2009-01-14  mse1397          No
29    ms170  2009-12-17  mse1398          No
..      ...         ...      ...         ...
762  ms1369  2010-12-02  mse2659          No
763  ms1369  2013-05-20  mse4670          No
764  ms1369  2014-08-13  mse4671          No
765  ms1369  2015-10-01  mse3671          No
766  ms1369  2017-01-12  mse7421          No
767  ms1462  2008-04-24  mse2691          No
768  ms1462  2009-03-10  mse2692          No
769  ms1462  2010-03-18  mse2693          No
770  ms1462  2013-01-30  mse7538          No
771  ms1462  2015-05-06  mse2908          No
772  ms1462  2016-07-27  mse6565          No
773  ms1578  2011-01-26  mse4238          No
774  ms1578  2011-06-21  mse4782          No
775  ms1578  2013-07-23  mse4702          No
776  ms1578  2014-08-27  mse4703          No
777  ms1578  2015-06-15  mse3029          No
778  ms1578  2016-07-05  mse5854          No
0     ms170  2012-12-10  mse4868         Yes
1     ms512  2012-12-12  mse4877         Yes
2     ms513  2012-10-31  mse4878         Yes
3     ms564  2012-10-22  mse4893         Yes
4     ms568  2013-01-03  mse4894         Yes
5     ms577  2012-11-05  mse4895         Yes
6     ms667  2013-01-07  mse4905         Yes
7     ms729  2013-01-24  mse4914         Yes
8     ms756  2012-11-07  mse4916         Yes
9     ms897  2012-08-23  mse4924         Yes
10   ms1136  2012-11-28  mse4928         Yes
11   ms1244  2012-10-15  mse2446         Yes
12   ms1279  2012-10-01  mse4933         Yes

[792 rows x 4 columns]

In [34]:
len_result = len(result['msid'])
print(len_result)

792

In [39]:
result.index = range(len_result)
result

       msid        date      mse qb3_scanner
0      ms69  2005-04-20  mse1343          No
1      ms69  2006-05-02  mse1344          No
2      ms69  2007-04-10  mse1345          No
3      ms69  2008-05-20  mse1346          No
4      ms69  2009-04-08  mse1347          No
5      ms69  2010-04-08  mse1348          No
6      ms69  2013-05-22  mse4287          No
7      ms71  2005-03-23  mse1355          No
8      ms71  2006-05-17  mse1356          No
9      ms71  2007-06-19  mse1357          No
10     ms71  2008-08-27  mse1358          No
11     ms71  2009-08-05  mse1359          No
12     ms71  2010-08-03  mse1360          No
13     ms71  2013-05-13  mse4291          No
14     ms71  2015-06-18  mse3041          No
15     ms71  2016-04-12  mse5276          No
16     ms73  2005-04-13  mse1361          No
17     ms73  2006-04-05  mse1362          No
18     ms73  2007-03-14  mse1363          No
19     ms73  2008-06-19  mse1364          No
20     ms73  2009-07-09  mse1365          No
21     ms73  2010-06-10  mse1366          No
22     ms73  2014-05-07  mse4292          No
23     ms73  2014-05-07  mse4293          No
24    ms170  2005-02-01     mse1          No
25    ms170  2006-02-28  mse1395          No
26    ms170  2007-01-31     mse2          No
27    ms170  2008-03-27  mse1396          No
28    ms170  2009-01-14  mse1397          No
29    ms170  2009-12-17  mse1398          No
..      ...         ...      ...         ...
762  ms1369  2010-12-02  mse2659          No
763  ms1369  2013-05-20  mse4670          No
764  ms1369  2014-08-13  mse4671          No
765  ms1369  2015-10-01  mse3671          No
766  ms1369  2017-01-12  mse7421          No
767  ms1462  2008-04-24  mse2691          No
768  ms1462  2009-03-10  mse2692          No
769  ms1462  2010-03-18  mse2693          No
770  ms1462  2013-01-30  mse7538          No
771  ms1462  2015-05-06  mse2908          No
772  ms1462  2016-07-27  mse6565          No
773  ms1578  2011-01-26  mse4238          No
774  ms1578  2011-06-21  mse4782          No
775  ms1578  2013-07-23  mse4702          No
776  ms1578  2014-08-27  mse4703          No
777  ms1578  2015-06-15  mse3029          No
778  ms1578  2016-07-05  mse5854          No
779   ms170  2012-12-10  mse4868         Yes
780   ms512  2012-12-12  mse4877         Yes
781   ms513  2012-10-31  mse4878         Yes
782   ms564  2012-10-22  mse4893         Yes
783   ms568  2013-01-03  mse4894         Yes
784   ms577  2012-11-05  mse4895         Yes
785   ms667  2013-01-07  mse4905         Yes
786   ms729  2013-01-24  mse4914         Yes
787   ms756  2012-11-07  mse4916         Yes
788   ms897  2012-08-23  mse4924         Yes
789  ms1136  2012-11-28  mse4928         Yes
790  ms1244  2012-10-15  mse2446         Yes
791  ms1279  2012-10-01  mse4933         Yes

[792 rows x 4 columns]

In [40]:
result['status'] = pd.Series(['NotRun'] * len_result, index=result.index)
result

       msid        date      mse qb3_scanner  status
0      ms69  2005-04-20  mse1343          No  NotRun
1      ms69  2006-05-02  mse1344          No  NotRun
2      ms69  2007-04-10  mse1345          No  NotRun
3      ms69  2008-05-20  mse1346          No  NotRun
4      ms69  2009-04-08  mse1347          No  NotRun
5      ms69  2010-04-08  mse1348          No  NotRun
6      ms69  2013-05-22  mse4287          No  NotRun
7      ms71  2005-03-23  mse1355          No  NotRun
8      ms71  2006-05-17  mse1356          No  NotRun
9      ms71  2007-06-19  mse1357          No  NotRun
10     ms71  2008-08-27  mse1358          No  NotRun
11     ms71  2009-08-05  mse1359          No  NotRun
12     ms71  2010-08-03  mse1360          No  NotRun
13     ms71  2013-05-13  mse4291          No  NotRun
14     ms71  2015-06-18  mse3041          No  NotRun
15     ms71  2016-04-12  mse5276          No  NotRun
16     ms73  2005-04-13  mse1361          No  NotRun
17     ms73  2006-04-05  mse1362          No  NotRun
18     ms73  2007-03-14  mse1363          No  NotRun
19     ms73  2008-06-19  mse1364          No  NotRun
20     ms73  2009-07-09  mse1365          No  NotRun
21     ms73  2010-06-10  mse1366          No  NotRun
22     ms73  2014-05-07  mse4292          No  NotRun
23     ms73  2014-05-07  mse4293          No  NotRun
24    ms170  2005-02-01     mse1          No  NotRun
25    ms170  2006-02-28  mse1395          No  NotRun
26    ms170  2007-01-31     mse2          No  NotRun
27    ms170  2008-03-27  mse1396          No  NotRun
28    ms170  2009-01-14  mse1397          No  NotRun
29    ms170  2009-12-17  mse1398          No  NotRun
..      ...         ...      ...         ...     ...
762  ms1369  2010-12-02  mse2659          No  NotRun
763  ms1369  2013-05-20  mse4670          No  NotRun
764  ms1369  2014-08-13  mse4671          No  NotRun
765  ms1369  2015-10-01  mse3671          No  NotRun
766  ms1369  2017-01-12  mse7421          No  NotRun
767  ms1462  2008-04-24  mse2691          No  NotRun
768  ms1462  2009-03-10  mse2692          No  NotRun
769  ms1462  2010-03-18  mse2693          No  NotRun
770  ms1462  2013-01-30  mse7538          No  NotRun
771  ms1462  2015-05-06  mse2908          No  NotRun
772  ms1462  2016-07-27  mse6565          No  NotRun
773  ms1578  2011-01-26  mse4238          No  NotRun
774  ms1578  2011-06-21  mse4782          No  NotRun
775  ms1578  2013-07-23  mse4702          No  NotRun
776  ms1578  2014-08-27  mse4703          No  NotRun
777  ms1578  2015-06-15  mse3029          No  NotRun
778  ms1578  2016-07-05  mse5854          No  NotRun
779   ms170  2012-12-10  mse4868         Yes  NotRun
780   ms512  2012-12-12  mse4877         Yes  NotRun
781   ms513  2012-10-31  mse4878         Yes  NotRun
782   ms564  2012-10-22  mse4893         Yes  NotRun
783   ms568  2013-01-03  mse4894         Yes  NotRun
784   ms577  2012-11-05  mse4895         Yes  NotRun
785   ms667  2013-01-07  mse4905         Yes  NotRun
786   ms729  2013-01-24  mse4914         Yes  NotRun
787   ms756  2012-11-07  mse4916         Yes  NotRun
788   ms897  2012-08-23  mse4924         Yes  NotRun
789  ms1136  2012-11-28  mse4928         Yes  NotRun
790  ms1244  2012-10-15  mse2446         Yes  NotRun
791  ms1279  2012-10-01  mse4933         Yes  NotRun

[792 rows x 5 columns]

In [41]:
result.to_csv('/data/henry7/james/antje_cohort/check_lesion_reg_status.csv')

In [6]:
import pandas as pd
status = pd.read_csv('/data/henry7/james/antje_cohort/check_lesion_reg_status.csv')
status.loc[status['msid'] == 'ms71', 'status'] = 'No_FLAIR_Lesion'
status

     Unnamed: 0    msid        date      mse qb3_scanner           status
0             0    ms69  2005-04-20  mse1343          No           NotRun
1             1    ms69  2006-05-02  mse1344          No           NotRun
2             2    ms69  2007-04-10  mse1345          No           NotRun
3             3    ms69  2008-05-20  mse1346          No           NotRun
4             4    ms69  2009-04-08  mse1347          No           NotRun
5             5    ms69  2010-04-08  mse1348          No           NotRun
6             6    ms69  2013-05-22  mse4287          No           NotRun
7             7    ms71  2005-03-23  mse1355          No  No_FLAIR_Lesion
8             8    ms71  2006-05-17  mse1356          No  No_FLAIR_Lesion
9             9    ms71  2007-06-19  mse1357          No  No_FLAIR_Lesion
10           10    ms71  2008-08-27  mse1358          No  No_FLAIR_Lesion
11           11    ms71  2009-08-05  mse1359          No  No_FLAIR_Lesion
12           12    ms71  2010-08-03  mse1360          No  No_FLAIR_Lesion
13           13    ms71  2013-05-13  mse4291          No  No_FLAIR_Lesion
14           14    ms71  2015-06-18  mse3041          No  No_FLAIR_Lesion
15           15    ms71  2016-04-12  mse5276          No  No_FLAIR_Lesion
16           16    ms73  2005-04-13  mse1361          No           NotRun
17           17    ms73  2006-04-05  mse1362          No           NotRun
18           18    ms73  2007-03-14  mse1363          No           NotRun
19           19    ms73  2008-06-19  mse1364          No           NotRun
20           20    ms73  2009-07-09  mse1365          No           NotRun
21           21    ms73  2010-06-10  mse1366          No           NotRun
22           22    ms73  2014-05-07  mse4292          No           NotRun
23           23    ms73  2014-05-07  mse4293          No           NotRun
24           24   ms170  2005-02-01     mse1          No           NotRun
25           25   ms170  2006-02-28  mse1395          No           NotRun
26           26   ms170  2007-01-31     mse2          No           NotRun
27           27   ms170  2008-03-27  mse1396          No           NotRun
28           28   ms170  2009-01-14  mse1397          No           NotRun
29           29   ms170  2009-12-17  mse1398          No           NotRun
..          ...     ...         ...      ...         ...              ...
762         762  ms1369  2010-12-02  mse2659          No           NotRun
763         763  ms1369  2013-05-20  mse4670          No           NotRun
764         764  ms1369  2014-08-13  mse4671          No           NotRun
765         765  ms1369  2015-10-01  mse3671          No           NotRun
766         766  ms1369  2017-01-12  mse7421          No           NotRun
767         767  ms1462  2008-04-24  mse2691          No           NotRun
768         768  ms1462  2009-03-10  mse2692          No           NotRun
769         769  ms1462  2010-03-18  mse2693          No           NotRun
770         770  ms1462  2013-01-30  mse7538          No           NotRun
771         771  ms1462  2015-05-06  mse2908          No           NotRun
772         772  ms1462  2016-07-27  mse6565          No           NotRun
773         773  ms1578  2011-01-26  mse4238          No           NotRun
774         774  ms1578  2011-06-21  mse4782          No           NotRun
775         775  ms1578  2013-07-23  mse4702          No           NotRun
776         776  ms1578  2014-08-27  mse4703          No           NotRun
777         777  ms1578  2015-06-15  mse3029          No           NotRun
778         778  ms1578  2016-07-05  mse5854          No           NotRun
779         779   ms170  2012-12-10  mse4868         Yes           NotRun
780         780   ms512  2012-12-12  mse4877         Yes           NotRun
781         781   ms513  2012-10-31  mse4878         Yes           NotRun
782         782   ms564  2012-10-22  mse4893         Yes           NotRun
783         783   ms568  2013-01-03  mse4894         Yes           NotRun
784         784   ms577  2012-11-05  mse4895         Yes           NotRun
785         785   ms667  2013-01-07  mse4905         Yes           NotRun
786         786   ms729  2013-01-24  mse4914         Yes           NotRun
787         787   ms756  2012-11-07  mse4916         Yes           NotRun
788         788   ms897  2012-08-23  mse4924         Yes           NotRun
789         789  ms1136  2012-11-28  mse4928         Yes           NotRun
790         790  ms1244  2012-10-15  mse2446         Yes           NotRun
791         791  ms1279  2012-10-01  mse4933         Yes           NotRun

[792 rows x 6 columns]